[package]
name = "vimci-tui"
description = "Optional terminal frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
vimci-app.workspace = true
vimci-present.workspace = true
