[package]
name = "davimci-tui"
description = "Optional terminal frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
davimci-app.workspace = true
davimci-core.workspace = true
davimci-keys.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[dev-dependencies]
davimci-app = { workspace = true, features = ["testing"] }
davimci-cmd = { workspace = true }
davimci-core = { workspace = true, features = ["testing"] }
davimci-headless.workspace = true
davimci-gui.workspace = true
